modLoader="javafml"
loaderVersion="[49,)"
license="GNU GPL 3.0"

[[mods]]
modId="potato_golem"
version="${version}"
displayName="potato golem :3"
logoFile="icon.png"
authors="thePlaceholder, Wholesa"
description='''
adds a potato golem to minecraft
'''

[[dependencies.potato_golem]]
   modId="forge"
   mandatory=true
   versionRange="[49,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.potato_golem]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.4,1.21)"
   ordering="NONE"
   side="BOTH"
